### ISSUE TITLE
[Bug] Loss=-1.0 and GPU memory keeps increasing in pipeline parallel

### ISSUE THREAD

**Issue by leeeizhang** [pytorch/torchtitan#547]
```toml
[experimental]
pipeline_parallel_degree = 2
pipeline_parallel_microbatches = 2
pipeline_parallel_split_points = ["layers.16"]
```
![img_v3_02dt_3762c001-9e4b-4b29-b4dd-8a19f0e33c0g](https://github.com/user-attachments/assets/b648c67e-d87e-46ee-9a64-e67d491f2465)
